name: keyforgery
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+33

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter_native_splash: ^2.2.11
  retrofit: '>=3.0.0 <4.0.0'
  json_annotation: '>=4.7.0'
  material_floating_search_bar: ^0.3.7
  material_design_icons_flutter: 5.0.6996
  settings_ui: 2.0.2
  dio: ^4.0.6
  logger: any
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  google_nav_bar: ^5.0.6
  cached_network_image: ^3.2.2
  localstore: ^1.2.3
  localstorage: ^4.0.0+1
  get_it: ^7.2.0
  pretty_dio_logger: ^1.2.0-beta-1
  drop_down_list: ^0.0.4
  shared_preferences: ^2.0.15
  executorservices: ^2.0.3
  floor: ^1.3.0
  percent_indicator: ^4.2.2
  flutter_svg: ^2.0.5
  scrollable_positioned_list: ^0.3.5
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: '>=4.0.0 <5.0.0'
  build_runner: '>2.3.0 <4.0.0'
  floor_generator: ^1.3.0
  json_serializable: '>4.4.0'

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Heebo
      fonts:
        - asset: assets/fonts/Heebo-VariableFont_wght.ttf
        - asset: assets/fonts/Heebo-Regular.ttf
